SET NAMES utf8;

CREATE DATABASE IF NOT EXISTS prdb DEFAULT CHARACTER SET utf8;

CREATE TABLE prdb.goods (
	uid INT UNSIGNED AUTO_INCREMENT,
	barcode VARCHAR(255) NOT NULL UNIQUE,
	pname VARCHAR(50) NOT NULL,
	price CHAR(11) NOT NULL,
	pnumber varchar(255) NOT NULL,
	PRIMARY KEY (uid)
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARACTER SET utf8;

-- CREATE USER 'dj'@'127.0.0.1' IDENTIFIED BY '123456';
-- GRANT ALL ON mydb.* to 'dj'@'127.0.0.1';
-- FLUSH PRIVILEGES;
